# settings controlling the synthesizer behaviour
name: "default_synthesizer"

query_generation:
  function_docs: examples/function_docs.json

  languages: 
    - English
    - Chinese
    - Japanese
    - German
#    - French
#    - Spanish

  name: "ugreen_function"
  output_dir: "data"
  output_format: "jsonl"   # or "json", "csv", "parquet"


function_call_generation:
  function_dataset: "data/ugreen_function/"
  max_num: 101 # max number of function calls to generate, -1 means all
  output_dir: "data"
  output_format: "jsonl"   # or "json", "csv", "parquet"
  name: "data/ugreen_function_call"