# structured config for LLM settings
# name is optional identifier
name: default_llm

providers:
  openai:
    backend: "openai"
    models:
      - "gpt-4o"
      - "gpt-4o-mini"
      - "gpt-3.5-turbo"
  
  anthropic:
    backend: "openai"
    models:
      - "claude-sonnet-4-20250514"
      - "claude-3-5-sonnet-20241022"


function_call:
  provider: openai
  model: gpt-4o
  backend: openai

